environment:

  PYTHON_ARCH: "64"
  PYTHON: "C:\\Miniconda36-x64"
  COMMIT_AUTHOR_EMAIL: "psyplot@hzg.de"

  matrix:
    - PYTHON_VERSION: "3.8"
      MPL_VERSION: "3.1"
      BUILD_STR_END: cf
    - PYTHON_VERSION: "3.7"
    - PYTHON_VERSION: "3.7"
      MPL_VERSION: "3.1"
      BUILD_STR_END: cf
    - PYTHON_VERSION: "3.7"
      MPL_VERSION: "3.0"
      BUILD_STR_END: cf
install:
    # windows config (for installation)
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - setlocal
    - set CONDA_REPO_TOKEN=
    # conda config
    - conda config --set always_yes yes --set changeps1 no
    - IF NOT DEFINED BUILD_STR_END (conda config --add channels chilipp) ELSE (conda config --add channels conda-forge)
    - conda config --add channels psyplot
    - conda update -q conda
    - conda install conda-build anaconda-client
    - conda info -a
    - conda list
    # windows config
    - endlocal
    - 'SET PYTHONWARNINGS=ignore:mode:DeprecationWarning:docutils.io:245'
    - "IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (SET GIT_BRANCH=%APPVEYOR_REPO_BRANCH%)"
    - "IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (conda config --add channels psyplot/label/master)"
    - "IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (conda config --add channels psyplot/label/%APPVEYOR_REPO_BRANCH%)"
    - python ci\\setup_append.py ci\\conda-recipe matplotlib=%MPL_VERSION%
    - IF DEFINED MPL_VERSION (set PSYPLOT_REFERENCES=%APPVEYOR_BUILD_FOLDER%/tests/reference_figures/win32/py%PYTHON_VERSION%/mpl%MPL_VERSION%)
    - IF DEFINED MPL_VERSION (set REFBRANCH=win32_py%PYTHON_VERSION%_mpl%MPL_VERSION%)
    - IF DEFINED PSYPLOT_REFERENCES (git submodule update --init %PSYPLOT_REFERENCES%)

build: off

test_script:
    - setlocal
    - set CONDA_REPO_TOKEN=
    - conda build ci/conda-recipe --python %PYTHON_VERSION%
    - IF DEFINED PSYPLOT_REFERENCES (python ci/check_ref_deploy.py)
    - endlocal

deploy_script:
    - "python ci\\deploy_anaconda.py"
    - IF EXIST deploy_references (IF %APPVEYOR_REPO_BRANCH%==master (python ci\update_reference_submodule.py))
    - IF EXIST deploy_references (IF %APPVEYOR_REPO_BRANCH%==master (ci\update_submodules.py))
