name: psyplot_docs
channels:
    - chilipp/label/dev
    - chilipp/label/master
    - chilipp
dependencies:
    - python=3.7
    - dask
    - xarray
    - netCDF4
    - matplotlib
    - seaborn
    - ipython
    - nbconvert
    - jupyter_client
    - ipykernel
    - sphinx
    - cartopy
    - psyplot
    - psy-simple
    - pip:
        - autodocsumm
        - sphinx-nbexamples
