name: psyplot_docs
channels:
    - chilipp/label/dev
    - conda-forge
dependencies:
    - python=3.6
    - dask
    - xarray
    - netCDF4
    - matplotlib
    - seaborn
    - ipython
    - nbconvert
    - jupyter_client
    - ipykernel
    - sphinx
    - cartopy
    - psyplot
    - psy-simple>1.0.1
    - pip:
        - autodocsumm
        - sphinx-nbexamples
